spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simpledb
    driverClassName: org.postgresql.Driver
    username: ernest
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: false
